### ISSUE TITLE
add npm publish to azure pipeline

### ISSUE THREAD

**Issue by cancerberoSgx** [KnicKnic/WASM-ImageMagick#27]
Would be awesome if you configure npm publish to azure pipelines as described here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml#publish-a-module-to-a-npm-registry

https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-npm?view=vsts&tabs=new-nav%2Cwindows#step-6-publish-an-npm-package

That way if there is any increment to pagkage.json version field and tests are green it wll automatically published to npm.

**Comment by KnicKnic** [comment]
I will try and look at this in the next few days. I would like to see add creating github releases as well, I don’t know how they deal with changelogs.

**Comment by KnicKnic** [comment]
Added an npm release pipeline. Due to https://github.com/Microsoft/azure-pipelines-tasks/issues/5380 it will fail every time the version is not updated.

https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_releaseProgress?_a=release-pipeline-progress&releaseId=44 is an example of a release that was auto scheduled and worked (it had a slight different workflow then below).

Since the build cannot go over 30 minutes or it gets shot. I did the following, let me know if it is safe to ignore scripts in the publish step.
1. npm install
2. npm test
3. npm publish **--ignore-scripts**
