### ISSUE TITLE
Multi-thread support

### ISSUE THREAD

**Issue by thibaultmol** [KnicKnic/WASM-ImageMagick#38]
So on linux we can use some tricks to use imagemagick in parallel. But on the WASM we're limited to the command line options box.

I know it's probably a lot of work to make it work, but for large image sets, it would be nice if it utilized all my cores (definitively now that processors with large amounts of  cores are getting more popular (Ryzen))

https://developers.google.com/web/updates/2018/10/wasm-threads

**Comment by KnicKnic** [comment]
For large files you will hit sandbox ram limit sizes. For large number of files, you can always spin up multiple web workers, but due to ram usage per worker I am not sure this would be the best idea.

See https://github.com/KnicKnic/WASM-ImageMagick/blob/master/src/magickApi.ts on how the worker is used.
